# ############################################################################################
# PROJET : Circuit de mesure des 3 Ros 
# DESCRIPTION : Contraintes de placement physique et verrouillage des primitives (LUTs).
# GÉNÉRATION : Ce fichier a été conçu via le script automatisé 'Constr.tcl'.
# AUTEUR : Consolé MBOUBA
# DATE : 24 Mars 2026
# ############################################################################################


set_property LOC SLICE_X6Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring*}]
set_property LOC SLICE_X6Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property LOC SLICE_X6Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property LOC SLICE_X6Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred_i_1}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred_i_1}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X6Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X6Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X6Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X6Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X6Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X6Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X6Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X6Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X6Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X6Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X6Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X6Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring*}]
set_property LOC SLICE_X7Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred_i_1__0}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred_i_1__0}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X7Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X7Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X7Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X7Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X7Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X7Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X7Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X7Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X7Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X7Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X7Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X7Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring*}]
set_property LOC SLICE_X8Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred_i_1__1}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred_i_1__1}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X8Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X8Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X8Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X8Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X8Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X8Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X8Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X8Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X8Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X8Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X8Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X8Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring*}]
set_property LOC SLICE_X10Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred_i_1__5}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred_i_1__5}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X10Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X10Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X10Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X10Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X10Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X10Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X10Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X10Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X10Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X10Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X10Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X10Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring*}]
set_property LOC SLICE_X11Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred_i_1__6}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred_i_1__6}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X11Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X11Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X11Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X11Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X11Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X11Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X11Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X11Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X11Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X11Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X11Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X11Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring*}]
set_property LOC SLICE_X12Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred_i_1__7}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred_i_1__7}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X12Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X12Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X12Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X12Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X12Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X12Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X12Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X12Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X12Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X12Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X12Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X12Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring*}]
set_property LOC SLICE_X13Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred_i_1__11}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred_i_1__11}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X13Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X13Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X13Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X13Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X13Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X13Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X13Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X13Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X13Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X13Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X13Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X13Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring*}]
set_property LOC SLICE_X15Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred_i_1__12}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred_i_1__12}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X15Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X15Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X15Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X15Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X15Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X15Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X15Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X15Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X15Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X15Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X15Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X15Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring*}]
set_property LOC SLICE_X17Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred_i_1__13}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred_i_1__13}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X17Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X17Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X17Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X17Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X17Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X17Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X17Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X17Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X17Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X17Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X17Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X17Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring*}]
set_property LOC SLICE_X18Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred_i_1__17}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring_inferred_i_1__17}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X18Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X18Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X18Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X18Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X18Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X18Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X18Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X18Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X18Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X18Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X18Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X18Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[0].Inst_Ro_B/ring*}]
set_property LOC SLICE_X21Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred_i_1__18}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring_inferred_i_1__18}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X21Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X21Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X21Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X21Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X21Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X21Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X21Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X21Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X21Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X21Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X21Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X21Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[1].Inst_Ro_B/ring*}]
set_property LOC SLICE_X22Y6 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred_i_1__19}]
set_property LOCK_PINS {I1:A1} [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred*}]
set_property LOCK_PINS {I1:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring_inferred_i_1__19}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOC SLICE_X22Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[0].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOC SLICE_X22Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[1].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOC SLICE_X22Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[2].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOC SLICE_X22Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[3].gate_inst}]
set_property BEL F6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOC SLICE_X22Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[4].gate_inst}]
set_property BEL G6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOC SLICE_X22Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[5].gate_inst}]
set_property BEL H6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOC SLICE_X22Y6 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[6].gate_inst}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOC SLICE_X22Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[7].gate_inst}]
set_property BEL B6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOC SLICE_X22Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[8].gate_inst}]
set_property BEL C6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOC SLICE_X22Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[9].gate_inst}]
set_property BEL D6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOC SLICE_X22Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[10].gate_inst}]
set_property BEL E6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOC SLICE_X22Y7 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property LOCK_PINS {I0:A1} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/P1_gen_ro[11].gate_inst}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_B[2].Inst_Ro_B/ring*}]
set_property LOC SLICE_X23Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred_i_1__2}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property LOC SLICE_X23Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/*}]
set_property LOC SLICE_X25Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred_i_1__3}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property LOC SLICE_X25Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/*}]
set_property LOC SLICE_X26Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred_i_1__4}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property LOC SLICE_X26Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[0].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/*}]
set_property LOC SLICE_X27Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred_i_1__8}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property LOC SLICE_X27Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/*}]
set_property LOC SLICE_X30Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred_i_1__9}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property LOC SLICE_X30Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/*}]
set_property LOC SLICE_X32Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred_i_1__10}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property LOC SLICE_X32Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[1].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/*}]
set_property LOC SLICE_X33Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred_i_1__14}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property LOC SLICE_X33Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/*}]
set_property LOC SLICE_X35Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred_i_1__15}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property LOC SLICE_X35Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/*}]
set_property LOC SLICE_X36Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred_i_1__16}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property LOC SLICE_X36Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[2].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/*}]
set_property LOC SLICE_X38Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/ring_inferred_i_1__20}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property LOC SLICE_X38Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[0].Inst_Ro_path/*}]
set_property LOC SLICE_X41Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/ring_inferred_i_1__21}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property LOC SLICE_X41Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[1].Inst_Ro_path/*}]
set_property LOC SLICE_X44Y1 [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells -hierarchical -filter {NAME =~ mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred*}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/ring_inferred_i_1__22}]
set_property BEL A6LUT [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property LOC SLICE_X44Y178 [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property LOCK_PINS {I0:A6} [get_cells {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/S1}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {mesure_i/All_Ro_out_0/U0/I_Ro_out[3].Inst_Ro_out/I_Ro_bench/I_RO_PATH[2].Inst_Ro_path/*}]
